apiVersion: apps/v1
kind: Deployment
metadata:
  name: "httpd-deployment"
spec:
  selector:
    matchLabels:
      app: "httpd"
  replicas: 3
  template:
    metadata:
      labels:
        app: "httpd"
    spec:
      containers:
      - name: httpd
        image: 759294595201.dkr.ecr.us-east-1.amazonaws.com/eks-demo-repo:latest
        ports:
        - containerPort: 80